openapi: 3.0.0
info:
  contact:
    email: apiteam@swagger.io
    name: Swagger API Team
    url: http://swagger.io
  description: A sample API that uses a petstore as an example to demonstrate features
    in the OpenAPI 3.0 specification
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Petstore
  version: 1.0.0
servers:
- url: https://DOMAIN.api.engagement.dimelo.com/1.0
paths:
  /teams:
    post:
      operationId: createTeam
      parameters:
      - description: tags to filter by
        explode: true
        in: query
        name: user_ids[]
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Team'
                type: array
          description: pet response
components:
  schemas:
    Team:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        user_ids:
        - user_ids
        - user_ids
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        leader_ids:
        - leader_ids
        - leader_ids
      properties:
        id:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        name:
          type: string
        leader_ids:
          items:
            type: string
          type: array
        user_ids:
          items:
            type: string
          type: array
