openapi: 3.0.1
info:
  termsOfService: https://developer.ringcentral.com
  title: Engage Digital API
  version: "1.0"
servers:
- url: https://DOMAIN.api.engagement.dimelo.com/1.0
tags:
- name: Communities
- name: Folders
- name: Sources
- name: Teams
paths:
  /communities:
    get:
      description: This method renders communities ordered by creation date (ascending).
      operationId: getAllCommunities
      parameters:
      - description: The record index to start. Default value is 0.
        in: query
        name: offset
        schema:
          type: integer
      - description: The max number of records to return. Default value is 30, max
          value is 150.
        in: query
        name: limit
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllCommunitiesResponse'
          description: Success
      summary: Getting all communities
      tags:
      - Communities
  /communities/{communityId}:
    get:
      description: This method renders a community from given id.
      operationId: getCommunity
      parameters:
      - in: path
        name: communityId
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Community'
          description: Success
      summary: Getting a community from its id
      tags:
      - Communities
  /content_sources:
    get:
      description: This method renders sources ordered by creation date (ascending).
      operationId: getAllSources
      parameters:
      - description: The record index to start. Default value is 0.
        in: query
        name: offset
        schema:
          type: integer
      - description: The max number of records to return. Default value is 30, max
          value is 150.
        in: query
        name: limit
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllSourcesResponse'
          description: Success
      summary: Getting all sources
      tags:
      - Sources
  /content_sources/{sourceId}:
    get:
      description: This method renders a source from given id.
      operationId: getSource
      parameters:
      - in: path
        name: sourceId
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: Success
      summary: Getting a source from its id
      tags:
      - Sources
  /folders:
    get:
      description: This method renders folders.
      operationId: getAllFolders
      parameters:
      - description: The record index to start. Default value is 0.
        in: query
        name: offset
        schema:
          type: integer
      - description: The max number of records to return. Default value is 30, max
          value is 150.
        in: query
        name: limit
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllFoldersResponse'
          description: Success
      summary: Getting all folders
      tags:
      - Folders
  /folders/{folderId}:
    get:
      description: This method renders a folder from given id.
      operationId: getFolder
      parameters:
      - in: path
        name: folderId
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folder'
          description: Success
      summary: Getting a folder from its id
      tags:
      - Folders
  /teams:
    get:
      description: This method renders teams ordered by creation date (ascending).
      operationId: getAllTeams
      parameters:
      - description: The record index to start. Default value is 0.
        in: query
        name: offset
        schema:
          type: integer
      - description: The max number of records to return. Default value is 30, max
          value is 150.
        in: query
        name: limit
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllTeamsResponse'
          description: Success
      summary: Getting all teams
      tags:
      - Teams
  /teams/{teamId}:
    get:
      description: This method renders a team from given id.
      operationId: getTeam
      parameters:
      - in: path
        name: teamId
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Success
      summary: Getting a team from its id
      tags:
      - Teams
components:
  schemas:
    Community:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: name
        active: true
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        type: type
      properties:
        active:
          type: boolean
        created_at:
          format: date-time
          type: string
        id:
          type: string
        name:
          type: string
        type:
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
    Folder:
      example:
        render_threads_count: true
        updated_at: 2000-01-23T04:56:07.000+00:00
        parent_id: parent_id
        query: query
        created_at: 2000-01-23T04:56:07.000+00:00
        role_restriction: '{}'
        id: id
        label: label
        position: 5
      properties:
        created_at:
          format: date-time
          type: string
        id:
          type: string
        label:
          type: string
        parent_id:
          type: string
        position:
          type: integer
        query:
          type: string
        render_threads_count:
          type: boolean
        role_restriction:
          type: object
        updated_at:
          format: date-time
          type: string
      type: object
    GetAllCommunitiesResponse:
      example:
        offset: 1
        records:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          active: true
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          type: type
        - updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          active: true
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          type: type
        count: 0
        limit: 6
      properties:
        count:
          format: int32
          type: integer
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
        records:
          items:
            $ref: '#/components/schemas/Community'
          type: array
      type: object
    GetAllFoldersResponse:
      example:
        offset: 1
        records:
        - render_threads_count: true
          updated_at: 2000-01-23T04:56:07.000+00:00
          parent_id: parent_id
          query: query
          created_at: 2000-01-23T04:56:07.000+00:00
          role_restriction: '{}'
          id: id
          label: label
          position: 5
        - render_threads_count: true
          updated_at: 2000-01-23T04:56:07.000+00:00
          parent_id: parent_id
          query: query
          created_at: 2000-01-23T04:56:07.000+00:00
          role_restriction: '{}'
          id: id
          label: label
          position: 5
        count: 0
        limit: 6
      properties:
        count:
          format: int32
          type: integer
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
        records:
          items:
            $ref: '#/components/schemas/Folder'
          type: array
      type: object
    GetAllSourcesResponse:
      example:
        offset: 1
        records:
        - error_message: error_message
          sla_response: 7
          default_category_ids:
          - default_category_ids
          - default_category_ids
          color: 5
          default_content_language: default_content_language
          sla_expired_strategy: sla_expired_strategy
          active: true
          created_at: 2000-01-23T04:56:07.000+00:00
          content_archiving: true
          content_languages:
          - content_languages
          - content_languages
          type: type
          auto_detect_content_language: true
          content_archiving_period: 5
          intervention_messages_boost: 2
          community_id: community_id
          time_sheet_ids:
          - time_sheet_ids
          - time_sheet_ids
          updated_at: 2000-01-23T04:56:07.000+00:00
          transferred_tasks_boost: 9
          name: name
          id: id
          channel_id: channel_id
          user_thread_default_category_ids:
          - user_thread_default_category_ids
          - user_thread_default_category_ids
          hidden_from_stats: true
          status: status
        - error_message: error_message
          sla_response: 7
          default_category_ids:
          - default_category_ids
          - default_category_ids
          color: 5
          default_content_language: default_content_language
          sla_expired_strategy: sla_expired_strategy
          active: true
          created_at: 2000-01-23T04:56:07.000+00:00
          content_archiving: true
          content_languages:
          - content_languages
          - content_languages
          type: type
          auto_detect_content_language: true
          content_archiving_period: 5
          intervention_messages_boost: 2
          community_id: community_id
          time_sheet_ids:
          - time_sheet_ids
          - time_sheet_ids
          updated_at: 2000-01-23T04:56:07.000+00:00
          transferred_tasks_boost: 9
          name: name
          id: id
          channel_id: channel_id
          user_thread_default_category_ids:
          - user_thread_default_category_ids
          - user_thread_default_category_ids
          hidden_from_stats: true
          status: status
        count: 0
        limit: 6
      properties:
        count:
          format: int32
          type: integer
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
        records:
          items:
            $ref: '#/components/schemas/Source'
          type: array
      type: object
    GetAllTeamsResponse:
      example:
        offset: 1
        records:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          user_ids:
          - user_ids
          - user_ids
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          leader_ids:
          - leader_ids
          - leader_ids
        - updated_at: 2000-01-23T04:56:07.000+00:00
          user_ids:
          - user_ids
          - user_ids
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          leader_ids:
          - leader_ids
          - leader_ids
        count: 0
        limit: 6
      properties:
        count:
          format: int32
          type: integer
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
        records:
          items:
            $ref: '#/components/schemas/Team'
          type: array
      type: object
    Restriction:
      properties:
        only:
          items:
            type: string
          type: array
      type: object
    Source:
      example:
        error_message: error_message
        sla_response: 7
        default_category_ids:
        - default_category_ids
        - default_category_ids
        color: 5
        default_content_language: default_content_language
        sla_expired_strategy: sla_expired_strategy
        active: true
        created_at: 2000-01-23T04:56:07.000+00:00
        content_archiving: true
        content_languages:
        - content_languages
        - content_languages
        type: type
        auto_detect_content_language: true
        content_archiving_period: 5
        intervention_messages_boost: 2
        community_id: community_id
        time_sheet_ids:
        - time_sheet_ids
        - time_sheet_ids
        updated_at: 2000-01-23T04:56:07.000+00:00
        transferred_tasks_boost: 9
        name: name
        id: id
        channel_id: channel_id
        user_thread_default_category_ids:
        - user_thread_default_category_ids
        - user_thread_default_category_ids
        hidden_from_stats: true
        status: status
      properties:
        active:
          description: Activate/deactivate the source
          type: boolean
        auto_detect_content_language:
          description: Auto-detect content language (Boolean)
          type: boolean
        channel_id:
          type: string
        color:
          description: 'Color of the icon: Default: 0 Blue: 1 Green: 2 Turquoise:
            3 Purple: 4 Yellow: 5 Orange: 6 Red: 7 Asphalt: 8 Grey: 9'
          format: int32
          type: integer
        community_id:
          type: string
        content_archiving:
          description: Automatic archiving of old contents (Boolean)
          type: boolean
        content_archiving_period:
          description: Archive contents older than (seconds)
          format: int64
          type: integer
        content_languages:
          items:
            type: string
          type: array
        created_at:
          format: date-time
          type: string
        default_category_ids:
          description: Default categories
          items:
            type: string
          type: array
        default_content_language:
          description: Default content language
          type: string
        error_message:
          type: string
        hidden_from_stats:
          description: Hide from statistics
          type: boolean
        id:
          type: string
        intervention_messages_boost:
          description: Priority boost of messages with intervention
          format: int32
          type: integer
        name:
          description: Source name
          type: string
        sla_expired_strategy:
          description: SLA expired strategy ("max", "half" or "base")
          type: string
        sla_response:
          description: Response time (seconds)
          format: int32
          type: integer
        status:
          type: string
        time_sheet_ids:
          items:
            type: string
          type: array
        transferred_tasks_boost:
          description: Priority boost of transferred tasks
          format: int32
          type: integer
        type:
          type: string
        updated_at:
          format: date-time
          type: string
        user_thread_default_category_ids:
          description: Default categories (agent messages)
          items:
            type: string
          type: array
      type: object
    Team:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        user_ids:
        - user_ids
        - user_ids
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        leader_ids:
        - leader_ids
        - leader_ids
      properties:
        created_at:
          format: date-time
          type: string
        id:
          type: string
        leader_ids:
          items:
            type: string
          type: array
        name:
          type: string
        updated_at:
          format: date-time
          type: string
        user_ids:
          items:
            type: string
          type: array
      type: object
